# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: lsb_release -a
    displayName: 'Show release'
  - script: |
      pwd
      cat test
  
trigger:
  branches:
    include:
      - feature

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: lsb_release -a
    displayName: 'Show release'
  - script: |
      pwd
      cat test
