# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo lsb_release -a
    displayName: 'Show release'
- script: |
    sudo apt-get update
    sudo apt -y full-upgrade
  displayName: 'Updating packages'
- script: |
    sudo apt -y install openjdk-11-jre
  displayName: 'Install OpenJDK Java runtime'
  
